-------------------------------------------------------------------------------
Test set: max.com.junit5.objects.legacy.PersonUtilsTest
-------------------------------------------------------------------------------
Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.058 s <<< FAILURE! - in max.com.junit5.objects.legacy.PersonUtilsTest
test_ConstructorThrowsIllegalArgumentExceptionIfLocalDateProviderIsNull  Time elapsed: 0.001 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Messages did not match ==> expected: <localDateProvider has to be provided> but was: <localDateService has to be provided>
	at max.com.junit5.objects.legacy.PersonUtilsTest.test_ConstructorThrowsIllegalArgumentExceptionIfLocalDateProviderIsNull(PersonUtilsTest.java:41)

